name: auspex_lakehouse
version: "1.0.0"
profile: auspex_lakehouse
model-paths: ["models"]

models:
  auspex_lakehouse:
    bronze:
      +materialized: view
flags:
  require_generic_test_arguments_property: true